train: ./data/images/train  # relative path to train images
val: ./data/images/val  # relative path to val images
test: ./data/images/test # relative path to public test images

# Classes
num_class: 3  # number of classes
# names: ['0', '1', '2', '3', '4', '5', '6', '7']
names: ['no mask', 'mask', 'incorrect mask']


